DATASET:
  ./datasets/flickr8k

EPOCHS: 1
BATCH_SIZE: 64

N_HEADS : 4
NUM_ENCODER_LAYERS : 4
NUM_DECODER_LAYERS : 4
DIM_FF : 256
PATCH_SIZE: 16
HEIGHT : 224
WIDTH : 224

MAX_LEN : 128
VOCAB_SIZE : 128
